[env]
TERM = "xterm-256color"

[window]
startup_mode = "Fullscreen"
padding = { x = 2, y = 2}
option_as_alt = "Both"

[font]
size = 16

[font.normal]
family = "TX02 Nerd Font"
# family = "DepartureMono Nerd Font"
# family = "BoldPixels Nerd Font"
# family = "BerkeleyMono Nerd Font Mono"
style = "Condensed"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10_000

[mouse]
hide_when_typing = true

[cursor.style]
shape = "Block"

[debug]
render_timer = false

[general]
import = [
  "~/.config/alacritty/themes/black_and_white.toml"
]
