[colors.normal]
black = "#4b5563"
red = "#c4746e"
green = "#87a987"
yellow = "#c4b28a"
blue = "#d4d4d8"
magenta = "#9ca3af"
cyan = "#d4d4d8"
white = "#d4d4d8"

[colors.bright]
black = "#4b5563"
red = "#c4746e"
green = "#87a987"
yellow = "#c4b28a"
blue = "#9ca3af"
magenta = "#9ca3af"
cyan = "#9ca3af"
white = "#d4d4d8"

[colors.cursor]
text = "#030712"
cursor = "#d4d4d8"

[colors.selection]
text = "#030712"
background = "#d4d4d8"

[colors.primary]
background = "#181616"
foreground = "#c5c9c5"

[[colors.indexed_colors]]
index = 16
color = "#b6927b"

[[colors.indexed_colors]]
index = 17
color = "#b98d7b"

